# test.py

mode: "test"
project_name: "pooling-loss"
group_name: "test-poolingloss-512-msmarco-infonce"

data:
  ds_name: "all" # allnli, msmarco, booksum, all
  batch_size: 10
  tokenizer_name: "FacebookAI/roberta-base"
  max_length: 512
  padding: false # max_length
  map_batch_size: 1000
  load_from_cache_file: false
  shuffle: false # Set to false to get "curriculum learning" on unified data

model:
  base_model_name: "FacebookAI/roberta-base"
  disable_pe: false
  is_decoder_model: false
  pooling_method: "mean"

test:
  run_mteb: true
  tasks: ["MSMARCO", "FEVER"] #, "STSBenchmark", "SummEvalSummarization.v2"]
  # --- trainer ---
  device: "gpu"
  num_devices: 1
  process_group_backend: "gloo"
  # --- wandb ---
  use_wandb: true
