# tune.yml

mode: "tune"
project_name: "pooling-loss"
group_name: "tune-poolingloss-512-pairwisece"

data:
  ds_name: "all" # allnli, msmarco, booksum, all
  batch_size: 24
  tokenizer_name: "FacebookAI/roberta-base"
  max_length: 512
  padding: false # max_length
  map_batch_size: 1000
  load_from_cache_file: false
  shuffle: true # Set to false to get "curriculum learning" on unified data

model:
  base_model_name: "FacebookAI/roberta-base"
  is_decoder_model: false
  pooling_method: "mean"
  q: null # Only if quantile_li

tune:
  loss: "pairwise-ce" # info-nce, triplet, pairwise-ce
  tau: # Only from CE losses
    # null
    type: choice
    values: [0.05, 0.07, 0.1, 0.15, 0.2]
  margin: # Only for triplet loss
    null
    # type: uniform
    # min: 0.2
    # max: 0.8
  # --- optimizer ---
  lr:
    type: loguniform
    min: 7.0e-6
    max: 1.0e-4
  weight_decay:
    type: loguniform
    min: 0.01
    max: 0.2
  # --- trainer ---
  device: "gpu"
  num_devices_per_trial: 1
  num_cpus_per_trial: 10
  max_steps: -1
  max_epochs: 2
  log_every_n_steps: 10
  accumulate_grad_batches: 1
  gradient_clip_val: null
  precision: "16-mixed"
  # --- tuner ---
  metric: "val_auroc" # val_mrr, val_auroc
  mode: "max" # max, min
  num_samples: 40
  max_concurrent_trials: 3
  time_budget_s: 172800 # 48 h in s
  max_t: 2 # Same as number of epochs
  grace_period: 1
  val_check_interval: 0.5
  # --- wandb ---
  use_wandb: True
